version: '3.2'
services:
  ba-userservice:
    image: userservice:0.0.1-SNAPSHOT
    restart: always
  ba-backend:
    image: backend:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - ba-postgres
    environment:
      - spring_profiles_active=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ba-postgres:5432/beerrating_db
      - BEERADVISOR_USERSERVICE_URL=http://ba-userservice:9020
    ports:
      - 10010:9000
  ba-postgres:
    image: 'postgres:10'
    environment:
      - POSTGRES_PASSWORD=becks
      - POSTGRES_USER=karlheinz
      - POSTGRES_DB=beerrating_db
    volumes:
      #      - ./init-greeting-db.sql:/docker-entrypoint-initdb.d/init-greeting-db.sql
      - ./beeradvisor-db-data:/var/lib/postgresql/data
  ba-frontend:
    image: 'ba_frontend:latest'
    depends_on:
      - ba-backend
    ports:
      - 10080:80