type Beer  {
    id: ID!
    name: String!
    """
    Price must not be higher than **ten euros**
    """
    price: String!

    averageStars: Int!
}

type Query {
    beer(beerId: ID): Beer
    beers: [Beer!]!
}

type Rating {
  id: ID!

  comment: String!
  stars: Int!
}

extend type Beer {
    ratings: [Rating!]!
}

input AddRatingInput {
    beerId: ID!
    userId: ID!
    comment: String!
    stars: Int!
}

type AddRatingSuccess  {
    newRating: Rating!
}
type AddRatingError  {
    message: String!
    code: Int!
}

union AddRatingResult = AddRatingError | AddRatingSuccess

type Mutation {
    # addRating(ratingInput: AddRatingInput): Rating!

    addRating(ratingInput: AddRatingInput!): AddRatingResult!
}

